server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kjdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #InnoDB 支持事务
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
